version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opigir-byparr_server_1
      APP_PORT: 8191

  server:
    image: ghcr.io/thephaseless/byparr:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      HOST: 0.0.0.0
      PORT: 8191
      TZ: UTC