version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opigir-copyparty_server_1
      APP_PORT: 3923

  server:
    image: copyparty/ac:latest
    restart: on-failure
    stop_grace_period: 15s
    volumes:
      - /home/umbrel:/w:z
      - ${APP_DATA_DIR}:/cfg:z
    environment:
      TZ: UTC
      PYTHONUNBUFFERED: 1
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s